import { FaCogs, FaShieldAlt, FaIndustry, FaBullseye, FaEye, FaHeart, FaTrophy, FaCheckCircle, FaCertificate } from 'react-icons/fa'

export const whyUsCards = [
    {
        id: 'fabricacion',
        icon: FaCogs,
        title: 'Fabricación a Medida',
        description: 'Elaboramos piezas dimensionadas, molduras, polines y componentes estructurales hasta 7 metros de largo según requerimiento.',
    },
    {
        id: 'proteccion',
        icon: FaShieldAlt,
        title: 'Protección de la Madera',
        description: 'Disponemos de planta impregnadora certificada por la Universidad del Bío-Bío y opción de baño antimancha para proteger la madera.',
    },
    {
        id: 'soluciones',
        icon: FaIndustry,
        title: 'Soluciones para Industria y Construcción',
        description: 'Proveemos materiales para viviendas, cabañas, embalajes y fabricación de pallets.',
    },
]

export const stats = [
    {
        id: 'exp',
        icon: FaTrophy,
        number: '21 años',
        label: 'de experiencia',
        description: 'Más de dos décadas de presencia en el rubro maderero desarrollando soluciones para construcción, embalaje y sector industrial.',
    },
    {
        id: 'cumplimiento',
        icon: FaCheckCircle,
        number: '100%',
        label: 'cumplimiento operativo',
        description: 'Planificación y coordinación eficiente en producción y despacho, asegurando cumplimiento según los requerimientos acordados.',
    },
    {
        id: 'acreditados',
        icon: FaCertificate,
        number: '+10 años',
        label: 'acreditados',
        description: 'Planta impregnadora certificada por la Universidad del Bío-Bío, acreditada desde 2010 bajo estándares técnicos.',
    },
]

export const missionVisionValues = [
    {
        id: 'mision',
        icon: FaBullseye,
        title: 'Misión',
        content: 'Proveer productos de madera de la más alta calidad, utilizando procesos de elaboración e impregnación que garanticen durabilidad y satisfacción total para nuestros clientes.',
    },
    {
        id: 'vision',
        icon: FaEye,
        title: 'Visión',
        content: 'Ser una empresa confiable en la fabricación e impregnación de madera en el sur de Chile, enfocada a llegar tanto a empresas como a clientes particulares, ofreciendo productos de calidad que se adaptan a distintos proyectos y necesidades.',
    },
    {
        id: 'valores',
        icon: FaHeart,
        title: 'Valores',
        content: 'Calidad sin compromisos, honestidad en cada trato, respeto por el medio ambiente, innovación constante y compromiso total con nuestros clientes.',
    },
]

export const shippingLocations = [
    { id: 'cañete', title: 'Cañete' },
    { id: 'lebu', title: 'Lebu' },
    { id: 'concepcion', title: 'Concepción' },
    { id: 'talcahuano', title: 'Talcahuano' },
]

// Responsive hero slides. `src` is the 1920px fallback; `srcSet` lets the browser
// pick the smallest sufficient width (huge LCP win on mobile vs. always shipping 1920px).
// Variants generated by scripts/generate-hero-responsive.js (widths 640/1024/1536/1920).
const heroWidths = [640, 1024, 1536, 1920]
const heroSlide = (n) => ({
    src: `/hero/hero-${n}-1920.webp`,
    srcSet: heroWidths.map((w) => `/hero/hero-${n}-${w}.webp ${w}w`).join(', '),
})

export const heroBackgrounds = [heroSlide(1), heroSlide(2), heroSlide(3), heroSlide(4)]
